name: Publish Package

on:
  release:
    types: ['published']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Setup authentication token
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
    - name: Publish package
      run: |
        yarn build
        npm publish

